development:
  secret_key_base: secret_key_base
  aws:
    access_key_id: "access_key_id"
    secret_access_key: "secret_access_key"
    s3_bucket_name: "myapp-development"
test:
  secret_key_base: secret_key_base
  aws:
    access_key_id: "access_key_id"
    secret_access_key: "secret_access_key"
    s3_bucket_name: "myapp-development"
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>